version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      # Package SAM template of the main stack
      - sam package --template-file sam.yml --s3-bucket ${S3_BUCKET} --output-template-file template.yml
  #post_build:
  #  commands:
      # Run the unit tests
  #    - pytest tests/unit --cov=./
artifacts:
  secondary-artifacts:
    BuildArtifact:
      files:
        - template.yml
        - stage-test.json
        - stage-prod.json
    BuildArtifactDefinitions:
      files: 
        - api/api-definition.yml